### ISSUE TITLE
400 Bad Request when Saving Asset

### ISSUE THREAD

**Issue by readeharris** [thejonanshow/guard-shopify#1] opened 2012-04-12 02:56 UTC
Hi 1337,

Thanks for releasing this guard! I was just debating starting to write one of these myself and was happy to see you've already got a head start.

Unfortunately, I'm getting a 400 Bad Request error whenever I try to upload an Asset. I'm sure my API key and password are right and I followed all the instructions on the http://wiki.shopify.com/Shopify_Textmate_Bundle page to create a private app.

I recognize that this may not technically be an issue with your gem, but have you run into this issue before? Any suggestions?

Here's some output:

```
Guard could not detect any of the supported notification libraries.
Guard is now watching at '/Users/Reade/Sites/emmysorganics'
assets/ie.css was changed.
ERROR: Guard::Shopify failed to achieve its <run_on_change>, exception was:
ActiveResource::BadRequest: Failed.  Response code = 400.  Response message = Bad Request.
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/activeresource-3.2.3/lib/active_resource/connection.rb:130:in `handle_response'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/shopify_api-2.2.0/lib/active_resource/connection_ext.rb:9:in `handle_response_with_response_capture'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/activeresource-3.2.3/lib/active_resource/connection.rb:115:in `request'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/shopify_api-2.2.0/lib/active_resource/connection_ext.rb:13:in `request_with_detailed_log_subscriber'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/activeresource-3.2.3/lib/active_resource/connection.rb:92:in `block in put'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/activeresource-3.2.3/lib/active_resource/connection.rb:218:in `with_auth'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/activeresource-3.2.3/lib/active_resource/connection.rb:92:in `put'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/activeresource-3.2.3/lib/active_resource/base.rb:1354:in `update'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/activeresource-3.2.3/lib/active_resource/observing.rb:19:in `update_with_notifications'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/activeresource-3.2.3/lib/active_resource/base.rb:1156:in `save'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/activeresource-3.2.3/lib/active_resource/validations.rb:79:in `save_with_validation'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/activeresource-3.2.3/lib/active_resource/observing.rb:19:in `save_with_notifications'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-shopify-0.0.2/lib/guard/shopify.rb:64:in `upload_text_asset'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-shopify-0.0.2/lib/guard/shopify.rb:50:in `block in run_on_change'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-shopify-0.0.2/lib/guard/shopify.rb:36:in `each'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-shopify-0.0.2/lib/guard/shopify.rb:36:in `run_on_change'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:387:in `block in run_supervised_task'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:385:in `catch'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:385:in `run_supervised_task'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:341:in `run_on_change_task'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:279:in `block (2 levels) in run_on_change'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:319:in `block (3 levels) in run_on_guards'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:318:in `each'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:318:in `block (2 levels) in run_on_guards'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:317:in `catch'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:317:in `block in run_on_guards'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:316:in `each'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:316:in `run_on_guards'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:278:in `block in run_on_change'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:295:in `block in run'
<internal:prelude>:10:in `synchronize'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:292:in `run'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard.rb:277:in `run_on_change'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard/listener.rb:89:in `block (2 levels) in start_reactor'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard/listener.rb:85:in `loop'
/Users/Reade/.rvm/gems/ruby-1.9.2-p290@shopiflow/gems/guard-1.0.1/lib/guard/listener.rb:85:in `block in start_reactor'

Guard::Shopify has just been fired
```

Thanks!

**Comment by thejonanshow** [comment] 2012-04-12 03:19
You are the first to contact me about it! I am presently in an all consuming
training program but I will try to have a look tomorrow or on the weekend.

I will try to make sure it's working for you by Monday.

**Comment by readeharris** [comment] 2012-04-12 04:26
Thanks! No rush. I've got things working using RestClient instead of ShopifyAPI for now, as I was getting the same 400 error when I just went directly through the console using the documentation in https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/resources/asset.rb.

If you make any headway on the issue, let me know and I'm happy to contribute some tests and/or a fix.

**Comment by fawx** [comment] 2012-04-17 23:54
this very recent merge is possibly related: https://github.com/Shopify/shopify_api/pull/19

**Comment by thejonanshow** [comment] 2012-04-21 22:05
Thanks fawx for the heads up. I'd like to say I will have time to address this soon but I know I won't. I'll be out of Hungry Academy in 4 months but for now I'm on about 16hrs a day of code. :P

If either of you or a passerby finds the fix feel free to make a pull request!

**Comment by fawx** [comment] 2012-04-24 20:34
i'll keep an eye on shopify_api.  it seems the problem is just in the lack of current documentation.

**Comment by gerrit** [comment] 2012-05-01 15:06
With the code from https://github.com/1337807/guard-shopify/pull/2 this is now fixed for me

**Closed as completed** 2015-09-14 15:16 UTC
